// NexusKey - Localized String Dictionary (English translations)
// Vietnamese is the default language (text in HTML), only English needs mapping.
// Keys match data-i18n attributes in HTML elements.

var STRINGS = {
    en: {
        // ── Common (shared across dialogs) ──
        "close": "Close",
        "add": "+ Add",
        "delete": "- Delete",
        "application": "Application",
        "refresh_list": "Refresh list",
        "pick_window": "\uD83C\uDFAF Pick window",
        "excluded_apps_title": "Excluded Apps",
        "tsf_apps_title": "TSF Apps",
        "no_apps_found": "No applications found",
        "no_matching": "No matching results",
        "no_running_apps": "No running applications",

        // ── Settings dialog ──
        "s.pin": "Pin to top",
        "s.admin_running": "Running as Administrator",
        "s.input_method": "Input Method",
        "s.code_table": "Code Table",
        "s.switch_key": "Switch Key",
        "s.switch_key_title": "Switch key",
        "s.beep": "Beep Sound",
        "s.beep_tooltip": "Play sound when switching language",
        "s.smart_switch": "Smart app exclusion",
        "s.smart_switch_tooltip": "Auto-remember input mode per app",
        "s.enable_exclude": "Exclude apps",
        "s.list": "List",
        "s.exclude_tooltip": "Disable Vietnamese for listed apps",
        "s.enable_tsf": "Use TSF for apps",
        "s.tsf_tooltip": "Use TSF engine instead of hook for listed apps",
        "s.advanced": "Advanced settings",
        "s.tab_input": "Input",
        "s.tab_macro": "Macro",
        "s.tab_system": "System",
        "s.tab_about": "About",

        // Tab 1: Input
        "s.modern_ortho": "Place diacritics: o\u00E0, u\u00FD (not \u00F2a, \u00FAy)",
        "s.auto_caps": "Auto-capitalize first letter",
        "s.auto_off_by_url": "Auto-disable in web browser URL bar",
        "s.allow_zwjf": "Allow \"z w j f\" as initial consonants",
        "s.allow_zwjf_tooltip": "Allowed by default. Only needed when spell check is on",
        "s.spell_check": "Spell check",
        "s.restore_key": "Auto-restore keys on wrong word",
        "s.allow_english_bypass": "Allow English bypass (e.g. yes \u2192 \u00FDe)",
        "s.allow_english_bypass_tooltip": "Allow applying Vietnamese tone marks on English words or exceptions",
        "s.spell_exclusions": "Spell exclusions",
        "s.spell_exclusions_tooltip": "Abbreviation prefixes that bypass spell check (e.g. h\u0111, \u0111p). Prefix match, min 2 chars.",
        "s.app_encoding": "Per-app encoding",
        "s.config": "Configure",
        "s.temp_off_alt": "Disable NexusKey with Alt",
        "s.temp_off_alt_tooltip": "Double-tap Alt to disable Vietnamese input (avoid app menu conflicts)",

        // Tab 2: Macro
        "s.enable_macro": "Enable macro",
        "s.macro_english": "Use macro in English mode",
        "s.auto_caps_macro": "Auto-capitalize from macro",
        "s.quick_telex": "Quick double consonant",
        "s.quick_telex_tooltip": "cc=ch, gg=gi, kk=kh, nn=ng, qq=qu, pp=ph, tt=th, uu=ươ",
        "s.quick_start": "Quick start consonant",
        "s.quick_start_tooltip": "f\u2192ph, j\u2192gi, w\u2192qu",
        "s.quick_end": "Quick end consonant",
        "s.quick_end_tooltip": "g\u2192ng, h\u2192nh, k\u2192ch",
        "s.temp_off_macro": "Skip macro with Esc",
        "s.temp_off_macro_tooltip": "Press Esc before typing to skip macro for next word",
        "s.macro_table_btn": "Macro table...",

        // Tab 3: System
        "s.run_startup": "Run on Windows startup",
        "s.startup_mode": "Default mode",
        "s.startup_mode_v": "Vietnamese",
        "s.startup_mode_e": "English",
        "s.startup_mode_r": "Remember last",
        "s.show_startup": "Show settings on startup",
        "s.run_admin": "Run as Administrator",
        "s.desktop_shortcut": "Create desktop shortcut",
        "s.bg_opacity": "Background opacity",
        "s.icon_style": "Customize icon",
        "s.icon_style_color": "Default color",
        "s.icon_style_dark": "Dark",
        "s.icon_style_light": "Light",
        "s.icon_style_custom": "Custom",
        "s.icon_style_auto": "Auto",
        "s.english_ui": "English interface",
        "s.english_ui_tooltip": "Switch UI, menus, and notifications to English",
        "s.force_light_theme": "Always use light theme",
        "s.force_light_theme_tooltip": "Ignore Windows dark mode, always show light theme",
        "s.custom_colors": "Custom icon colors",
        "s.color_v": "Choose V color",
        "s.color_e": "Choose E color",
        "s.floating_icon": "Floating V/E icon",
        "s.floating_icon_tooltip": "Show floating icon. May reduce FPS in Fullscreen games (Borderless recommended)",

        // Tab 4: About
        "s.tagline": "Modern Vietnamese Input Method",
        "s.version_label": "Version:",
        "s.dev_label": "Author:",
        "s.origin_label": "Origin:",
        "s.origin_text": "Project inspired by OpenKey and VietType, aiming to improve the UI, engine, and add new features.",
        "s.license": "NexusKey is open-source, free, and non-profit software.",
        "s.auto_update": "Auto-check for updates",
        "s.check_now": "Check now",
        "s.update_tooltip": "Check for new version on startup",

        // ── Restart banner (hybrid TSF DLL update) ──
        "update.banner.pending":    "Update not finished. Restart Windows to apply the new TSF version.",
        "update.banner.mismatch":   "Some apps still run the old version. Restart Windows to sync.",
        "update.banner.restartNow": "Restart now",
        "update.banner.later":      "Later",
        "update.banner.confirm":    "Restart Windows now to finish the NexusKey update?",
        "s.report_issue_label": "Are you having problems?",
        "s.report_issue": "Report problem",

        // ── Macro dialog ──
        "m.title": "Macro Table",
        "m.shortcut": "Shortcut",
        "m.shortcut_ph": "e.g.: btw",
        "m.content": "Full content",
        "m.content_ph": "e.g.: by the way",
        "m.import": "Import from file...",
        "m.export": "Export to file...",
        "m.edit": "+ Edit",
        "m.hint_enter": "Press Enter for a new line",
        "m.hint_clipboard": "Long macros use Clipboard to paste (current Clipboard content will be overwritten)",
        "m.trigger_keys": "Trigger keys:",
        "m.trigger_arrows": "Arrows",

        // ── Spell Exclusions dialog ──
        "se.info": "Abbreviation prefixes that bypass spell check. Prefix match, min 2 chars. E.g.: h\u0111 covers h\u0111, h\u0111t, h\u0111qt...",
        "se.exclusion_list": "Exclusion list",
        "se.word": "Word",

        // ── Excluded Apps dialog ──
        "ea.app_ph": "e.g.: notepad.exe",
        "ea.excluded_list": "Excluded applications",
        "ea.import": "Import from file...",
        "ea.export": "Export to file...",

        // ── TSF Apps dialog ──
        "tsf.app_ph": "e.g.: notepad.exe",
        "tsf.app_list": "TSF applications",
        "tsf.import": "Import from file...",
        "tsf.export": "Export to file...",

        // ── Convert Tool dialog ──
        "ct.title": "Convert Tool",
        "ct.general": "General Options",
        "ct.to_upper": "Convert to UPPERCASE",
        "ct.to_lower": "Convert to lowercase",
        "ct.remove_marks": "Remove diacritics",
        "ct.auto_paste": "Auto paste + select",
        "ct.caps_first": "Capitalize first letter",
        "ct.caps_each": "Capitalize Each Word",
        "ct.alert_done": "Alert when done",
        "ct.sequential": "Sequential convert",
        "ct.sequential_tooltip": "Press hotkey multiple times to cycle through options. Only available when 'Auto paste + select' is on.",
        "ct.options": "Options",
        "ct.clipboard": "Convert from Clipboard",
        "ct.choose_file": "Choose file",
        "ct.source_file": "Source file",
        "ct.no_file": "No file selected...",
        "ct.source_title": "Select source file",
        "ct.dest_file": "Destination file",
        "ct.dest_title": "Select destination file",
        "ct.hotkey_label": "Quick conversion hotkey:",
        "ct.encoding": "Code Table",
        "ct.source": "Source",
        "ct.dest": "Destination",
        "ct.swap": "Swap encoding",
        "ct.convert": "Convert",

        // ── About dialog (standalone) ──
        "a.title": "About NexusKey",
        "a.tagline": "Modern Vietnamese Input Method",
        "a.repo_nexuskey": "NexusKey Repo",
        "a.repo_openkey": "Original OpenKey Repo",
        "a.footer": "Powered by Sciter.JS for a smooth experience.",

        // ── App Overrides dialog ──
        "ao.title": "App Override",
        "ao.input_method": "Input method",
        "ao.encoding": "Encoding",
        "ao.list_app": "Application",
        "ao.list_method": "Method",
        "ao.list_encoding": "Encoding",
        "ao.app_ph": "e.g.: myapp.exe"
    }
};
